### PR TITLE
Added support for Generic Location Global messages.

### PR DESCRIPTION
**Pull request by daretobeorjan**
First stab at adding messages to support the Global Location state. Tried to match other messages as best I could, but please let me know if I should re-arrange things.

Not tested on a live device, hoping the unit tests are good enough. The only thing I'm concerned about is the byte order, but since the generation of the message parameters is identical to old messages, I'm thinking it should be ok.

### CODE REVIEW

**Comment by philips77** [comment]
Thanks! That looks good! I'll review when I'm back in the office on August.

**Comment by daretobeorjan** [comment]
> Thanks! That looks good! I'll review when I'm back in the office on August.

Hi @philips77, are you back in the office yet?

**Comment by philips77** [comment]
Hi, yes, but need to close some other tasks before. But I should resume work on mesh this week. Sorry for the delay.

**Comment by philips77** [comment]
Excellent PR. Thank you. Merging.

**Pull request merged**
