### PR TITLE
Allow custom proxyfilter implementations

### PR DESCRIPTION
**Pull request by bspinner**
We need custom behaviour in different situations.
The easiest to allow for this are custom ProxyFilter-implementations.

Therefore I added a `ProxyFilter` protocol and renamed the existing implementation to `DefaultProxyFilter`.

### CODE REVIEW

**Comment by philips77** [comment]
Thank you, I'll go though it this week.
May I ask why do you need custom proxy filters and how this PR is related to the other one? Was your intention to replace it? What custom impl do you need besides the one I described in https://github.com/NordicSemiconductor/IOS-nRF-Mesh-Library/issues/386#issuecomment-989706034

**Comment by bspinner** [comment]
Yes, I think this could replace !387, since this changes would open the library for custom implementations.

We need/want to dynamically set inclusion/exclusion filters without setting a "wrong" filter type and address lists beforehand upon connection.
The default implementation would always set the default parameters first.

**Comment by philips77** [comment]
In my opinion this can be achieved easier with the approach I proposed in the mentioned comment. It would allow to set a filter type and list of addresses without the need to extend a filter with a custom class.

**Comment by bspinner** [comment]
If I understand your proposal correctly, the filter settings would be passed in the initializer and therefore would be static during the ProxyFilters lifetime?

We want to change the settings dynamically, so calls to reset and setup set the correct settings depending on situation without having to create a new Network.

**Comment by Eklow02** [comment]
I could use that in my case also well

**Comment by philips77** [comment]
> If I understand your proposal correctly, the filter settings would be passed in the initializer and therefore would be static during the ProxyFilters lifetime?

No, only the initial state of the Proxy filter would be passed in the initializer: automatic (current, with automatic inclusion list containing all node's unicast addresses, group addresses for which at least one local model is subscribed to, including 0xFFFF), inclusion list with given set of addresses and exclusion list of given addresses.

> We want to change the settings dynamically, so calls to reset and setup set the correct settings depending on situation without having to create a new Network.

The current API would be preserved.

> The changes I made should be free of breaking changes for users.

I agree, but to set a custom initial setup for the proxy filter requires extending the new protocol. In my opinion the same could be achieved with custom initial state of the filter. But I don't know what you have there, actually. Do you manage your filter dynamically from there, or just use it for the initial state?

**Comment by bspinner** [comment]
See #390

**Pull request closed without merging**
