### PR TITLE
Asynchronous message sending - with `associatedtype`

### PR DESCRIPTION
**Pull request by philips77**
This is a first approach to implement sending mesh messages using `async`/`await`.

Apart from adding this feature, all `StaticAcknowledgeMessage` have been refactored tu use `associatedtype` instead of `static let responseType: MeshResponse`. This, however, requires Swift 5.6 and keywords like `any` and `some`, so this is a breaking change.

The benefit: returned type of `send(message...)` is the actual type, not generic `MeshResponse`.

Is it worth it?

### CODE REVIEW

**Comment by eanderlind** [comment]
I have several reservations going in this direction:
1. I experimented using associatedType in Swift 5.7 or so and found it difficult to work with in practice. (Same comment applies to opaque types). I think there are some gaps that have since been addressed, but as a minimum it will cause support pain to those not on very recent version of Swift. I am not sure, but think once you start type-erasing using `some` and `any`, there may be some type errors that slip through e.g. if user cuts and pastes msg handling code and forgets to adjust one of the message names. The existing protocol hierarchy of message types appears to work well without introducing associatedType. 
2. As mentioned earlier, it would be desirable to provide a native async call rather than a wrapper using a completion handler. I am not sure, but one of the references I provided mentioned that when using a completion closure one can't use the `try catch` idiom that seems to fit the model msg receipt use case well.
3. MeshNetworkManager.swift introduces a generic for each message type. Won't this cause an undesirable increase in code size, since now need one function for each type of message that the node handles? Mesh 1.1 further increases number of msg types that need to be handled.

Instead of using associatedType, try using idioms
 `if let msg = message as? ConfigCompositionDataStatus`
or
`switch { case let msg as? ConfigCompositionDataStatus ...`
Because of the richly typed MeshMessage protocol hierarchy, shouldn't ever need a massive switch over all message opcodes. Model delegates will only need to switch over the opcodes it handles.

**Comment by philips77** [comment]
Thank you for your comments. I agree with 1. and perhaps 3. The only benefit is that your don't have to the idiom check for each message. I didn't migrate the sample app, so perhaps i missed a lot of issues.

Regarding 2. I need to read more about.

**Comment by philips77** [comment]
I gave some thought to that.

> it would be desirable to provide a native async call rather than a wrapper using a completion handler.

However I think about it, there's always a callback deep down at the very end. Some async request is made and response will trigger another code, which should resume the awaiting method. It's just a matter of there the callback is.

In this implementation I added callbacks to the `NetworkManager`, as that object already was getting events about sending success of failure and responses.

The one issue I see is that I am still using `DispatchQueue` and calling `queue.async { ... }` from within the new async methods, which is incorrect, as they are already in a separate thread. I tried converting `NetworkManager` to an `actor`, but that only moves the `withCheckedThrowableContinuation` there. With that I also have to increment minumum iOS version to 13 (bot a biggie) and fix million of issues related to this class being an actor now.

Another issue is, that with `NetworkManager` converted to `actor` the `send(...)` methods in the `MeshNetworkManager` need to either be async (and cannot return `MessageHandle`), or start a `Task` instead of `queue.async { ... }`.

**Comment by philips77** [comment]
Hi, could you check #527?

**Comment by eanderlind** [comment]
Is it correct understanding to view this pullrequest and #527 as two alternate approaches and intent is to ultimately pick one of them? Assuming this is the case, will initially focus on reviewing #527

**Comment by philips77** [comment]
This PR was replaced with #527.

**Pull request closed without merging**
