### PR TITLE
Redesigning models implementation

### PR DESCRIPTION
**Pull request by philips77**
This PR breaks a lot of API since the previous version.

In order to send and receive messages, the app needs to register a `Model Handler` in a `Model`. Handlers are required when the app adds a `Model` to a local `Element`.

This is how the sample app does this in `AppDelegate`:
```swift
// Set up local Elements on the phone.
let element0 = Element(name: "Primary Element", location: .first, models: [
    Model(sigModelId: 0x1000, handler: GenericOnOffServerHandler()),
    Model(sigModelId: 0x1002, handler: GenericLevelServerHandler()),
    Model(sigModelId: 0x1001, handler: GenericOnOffClientHandler()),
    Model(sigModelId: 0x1003, handler: GenericLevelClientHandler())
])
let element1 = Element(name: "Secondary Element", location: .second, models: [
    Model(sigModelId: 0x1000, handler: GenericOnOffServerHandler()),
    Model(sigModelId: 0x1002, handler: GenericLevelServerHandler()),
    Model(sigModelId: 0x1001, handler: GenericOnOffClientHandler()),
    Model(sigModelId: 0x1003, handler: GenericLevelClientHandler())
])
meshNetworkManager.localElements = [element0, element1]
```

A `ModelHandler` is responsible for defining message types that it can handle (pairs: [opcode : type]). The `manager.delegate` will receive an `UnknownMessage` unless there is at least one `ModelHandler` that can decode a message with some opcode. 

The same applies to vendor models. The `manager.register(vendorMessageType:)` messages has been removed. Now, the app needs to declare a model on the local element with a handler that declares the given message opcode.

For example, the sample app declares 2 elements (Configuration Server, Client and Health Server and Client are automatically added as first models of the first element) with Generic On Off Server, Client and Generic Level Server and Client (they are duplicated just to prove that the library supports multiple elements on the local node.

Screen Shot 2019-10-02 at 16 17 41

Local models can be configured as any other models on remote devices - by sending configuration messages. For example, it is now possible to set publication from a local Generic On Off Client model on Element 2 (or 1). This message can be received also by a local Generic On Off Server model on Element 2 (or 1).

### CODE REVIEW

**Comment by philips77** [comment]
CC: @icarus31 @Baothien1301 @d-srd @BubblyNetDev and others.

FYI: UI for local Generic OnOff Server and Generic Level Server doesn't work yet. I'll have to use observables here, I think. I'll continue working tomorrow.

**Comment by icarus31** [comment]
Hi,

I am a bit lost with the new way to handle the message when I want to use my vendor models. 

I tried to follow what you've done with GenericOnOff message, but it looks like I can't handle the status message received. I can see it as a "Response Access PDU", but my cell that was expecting the value does not receive the status.

Would you mind to guide me a little bit?

Thanks

**Comment by philips77** [comment]
Sure. First thing you have to do is to add your vendor model to a local element in the manager. It's enough to have just one element and add all models you need unless they repeat, then each repeating model must be in a new element. Together with the model you'll set a `ModelDelegate`. In this delegate you need to register your status message and it's opcode, like the sample app does. When registered, your model will receive `model(_:didReceiveResponse:toAcknowledgedMessage:from)` after sending your message. If you're using other element than the first one, remember to send the message giving the originating element.
As messages as sent using the manager, its delegate is also notified when a message was sent/received/failed to be delivered/failed to receive the status.
Make sure your request is an Acknowledged Message.

**Comment by philips77** [comment]
Step by step:
1. Create a static acknowledged message with a request and an unacknowledged message with response.
2. Set the response type in request's `responseType` parameter.
3. Create `ModelDelegate`, in which register your response opcode. You'll only use the last method, add your model only has a single opcode, that's sent as a response to the request. First two will not be called, unless your device will send a response message without being requested to do so.
4. Bind your model with the app key that you're using to send the request.
5. In the app, send the request from the model's parent element using `manager.send(_:from:to:...)`.
6. You should get the model delegate method called and also the manager delegate should also be notified that a message was received. The manager delegate will also be informed if the response didn't pass model filter, that is it was sent to a different unicast address, to a group that your model isn't subscribed to or encrypted using an app key not bound to your model. All those must be fulfilled in order to deliver the response to your model delegate.

**Pull request merged**
