### PR TITLE
Made rawValue methods on TransitionTime public

### PR DESCRIPTION
**Pull request by daretobeorjan**
This allows custom vendor implementations to use the code for parsing and writing transition times, instead of having to write identical code themselves.

### CODE REVIEW

**Review by philips77 — APPROVED** [review]

**Comment by philips77** [comment]
I understand the need for `Data` extensions, but why do you need `rawValue` from `TransitionTime`?

**Comment by philips77** [comment]
Could you please rebase onto `main`?

**Comment by philips77** [comment]
Also, you could split the PR into 2 for clarity.

**Comment by daretobeorjan** [comment]
> I understand the need for `Data` extensions, but why do you need `rawValue` from `TransitionTime`?

It might a bit of an edge-case, but some of our vendor models have been defined to have transition times in them, and when making our own parser for those messages, it would be nice to not have to do all the bit-shifting manually and instead just pass the raw value read from the message.

**Pull request closed without merging**
